Fix rosetta's geth args to no longer require genesis file
celo-org/rosetta pull request #177
Opened 2021-07-05 16:05 UTC by eelanagaraj

Up til now we have been pulling the genesis file from cloud storage, but this information is now stored in the celo-blockchain repo and we should use that as the source of truth.

2021-07-06 14:17 UTC, oneeman requested changes
Looks good, but I think you could go further in removing things.  When you run celo-blockchain for the first time it doesn't need an empty data directory to exist, it creates it by itself.  So for alfajores, baklava, and mainnet we could remove the `make foo-env` entirely, and remove the bullet point in their docs saying about having to run them.

Besides that, I just commented with a couple of nits.

2021-07-06 14:17 UTC, oneeman commented on README.md
> +      --geth.genesis string       path to the genesis.json (optional; useful for running Rosetta witha  custom chain)
```suggestion
      --geth.genesis string       path to the genesis.json (optional; useful for running Rosetta with a custom chain)
```

2021-07-06 14:17 UTC, oneeman commented on cmd/run.go
> +	flagSet.String("geth.network", "", "Network to use, either 'mainnet', 'alfajores', or 'baklava'")
This should also be marked a optional, since you specify either this or geth.genesis.

2021-07-09 16:52 UTC, eelanagaraj commented
thanks @oneeman! Looks like Rosetta does some additional datadir creation stuff before even calling geth (i.e. creating the `rosetta.db` at this location). I took out the pieces that were easy to remove and that wouldn't potentially disrupt any other parts of the service, though it still creates the dir before starting up the geth node -- maybe the full changes will be worth it in the future.

2021-07-09 19:05 UTC, oneeman approved these changes
Looks great!

2021-07-12 09:26 UTC, merged