Bump blockchain and kliento deps for v0.8.6
celo-org/rosetta pull request #182
Opened 2022-01-20 17:47 UTC by YoduYodu

2022-01-20 20:18 UTC, piersy requested changes
The version of kliento that is set in go.mod is not correct.

The [tag](https://github.com/celo-org/kliento/releases/tag/v0.2.1) although marked as upgrading to celo blockchain v1.5.0 actually is pointing at an earlier commit.

But even then we don't currently have a correct commit to point to, because the latest commit on master https://github.com/celo-org/kliento/commit/80b383b59796d565e3e853e9790343b30fb8f283 contains contract bindings generated for the core contracts at a version different to core-contracts.v5

So before we can consider merging this we need to fix kliento

2022-01-20 20:24 UTC, piersy commented
@YoduYodu I've deleted the v0.2.1 tag in kliento. So when kliento is updated with the correct contract bindings we can tag that as v0.2.1

2022-01-20 20:52 UTC, YoduYodu commented
> @YoduYodu I've deleted the v0.2.1 tag in kliento. So when kliento is updated with the correct contract bindings we can tag that as v0.2.1

Agree, just made this PR as draft.
I'll update Kliento once celo-blockchain v1.5.1 is released

2022-01-28 19:20 UTC, piersy commented
@YoduYodu the branch has conflicts

2022-01-28 20:06 UTC, piersy commented
Hey @YoduYodu I would suggest splitting this PR into one that updates deps and one that just handles bumping the version. This is definitely not just a bugfix, functionality has been changed so the version should be 0.9.0 I think.

2022-01-28 20:17 UTC, YoduYodu commented
> Hey @YoduYodu I would suggest splitting this PR into one that updates deps and one that just handles bumping the version.
I am not sure if these can be split, introducing v1.5.1 requires updating those APIs(e.g. `SendRawTransaction` -> `SendTransaction`) because celo-blockchain@v1.5.1 is not back compatible in terms of these "APIs"

2022-01-28 20:56 UTC, piersy commented
Hey @YoduYodu

What I meant by bumping the version was the change from v0.8.5 -> v0.8.6 I think that could be done separately from updating the code and the golang and celo-blockchain version changes.

With regards to choosing the version number, I assumed that Semantic Versioning is being used because we are specifying the version with 3 dot separated numbers, otherwise just a single number would suffice.

And in the case of Semantic Versioning the minor number is changed when backwards compatible functionality is added, which I would say has been done because new command flags have been added since the last release.

2022-01-28 21:00 UTC, piersy approved these changes
Looking good now!

2022-01-28 21:14 UTC, merged

2022-02-01 17:19 UTC, CryptoGodfatherVA2 reviewed
var5